apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitter-deployment
  labels:
    app: kitter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kitter
  template:
    metadata:
      labels:
        app: kitter
    spec:
      containers:
        - name: kitter-server
          image: kitter:v0.0.1
          command: ["kitter", "server"]
          ports:
            - containerPort: 5102
        - name: kitter-client
          image: kitter:v0.0.1
          command: [ '/bin/sh', '-c', '/usr/bin/tail -f /dev/null']
