---
apiVersion: v1
kind: Service
metadata:
  name: kitter-service
  labels:
    app: kitter
spec:
  type: ClusterIP
  ports:
    - port: 5102
      targetPort: 5102
      protocol: TCP
  selector:
    app: kitter

---
apiVersion: v1
kind: Service
metadata:
  name: kitter-headless-service
  labels:
    app: kitter
spec:
  clusterIP: None
  ports:
    - port: 5102
      targetPort: 5102
      protocol: TCP
  selector:
    app: kitter
